// Mocks generated by Mockito 5.4.2 from annotations
// in advicer/test/data/repository/repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:advicer/data/datasource/advice_remote_datasource.dart' as _i4;
import 'package:advicer/data/models/advicer_model.dart' as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAdvicerModel_1 extends _i1.SmartFake implements _i3.AdvicerModel {
  _FakeAdvicerModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdvicerRemoteDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdvicerRemoteDatasourceImpl extends _i1.Mock
    implements _i4.AdvicerRemoteDatasourceImpl {
  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);
  @override
  _i5.Future<_i3.AdvicerModel> getAdviceFromApi() => (super.noSuchMethod(
        Invocation.method(
          #getAdviceFromApi,
          [],
        ),
        returnValue: _i5.Future<_i3.AdvicerModel>.value(_FakeAdvicerModel_1(
          this,
          Invocation.method(
            #getAdviceFromApi,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.AdvicerModel>.value(_FakeAdvicerModel_1(
          this,
          Invocation.method(
            #getAdviceFromApi,
            [],
          ),
        )),
      ) as _i5.Future<_i3.AdvicerModel>);
}
